export const serviceToGalleryMap: Record<string, string> = {
    // ---- Română ----
    'Aplicare Glet': 'renovari-interioare',
    'Montaj Faianță': 'bai',
    'Montaj Gresie': 'bai',
    'Montaj Parchet': 'renovari-interioare',
    'Montaj Rigips': 'renovari-interioare',
    'Montaj Tapet': 'renovari-interioare', 
    'Piatra Naturală': 'spatii-comerciale',
    'Trepte': 'spatii-comerciale',
    'Turnare Șape': 'procese',
    'Vopseli': 'renovari-interioare',
    'Zidărie': 'procese',
    'Zugrăveli': 'renovari-interioare',
    'Centrale Termice': 'procese',
    'Consultanță Imobiliară': 'spatii-comerciale',
    'Design Interior': 'renovari-interioare',
    'Finisaje de Lux': 'renovari-interioare',
    'Instalații Electrice': 'procese',
    'Instalații Sanitare': 'bai',
    'Instalații Termice': 'procese',
    'Mobilă la Comandă': 'renovari-interioare',
    'Montaj Ferestre': 'spatii-comerciale',
    'Montaj Uși': 'spatii-comerciale',
    'Servicii Curățenie': 'procese',
  
    // ---- English ----
    'Plaster Application': 'renovari-interioare',
    'Tile Installation': 'bai',
    'Ceramic Tile Installation': 'bai',
    'Parquet Installation': 'renovari-interioare',
    'Drywall Installation': 'renovari-interioare',
    'Wallpaper Installation': 'renovari-interioare',
    'Natural Stone': 'spatii-comerciale',
    'Stairs': 'spatii-comerciale',
    'Floor Screeding': 'procese',
    'Paintwork': 'renovari-interioare',
    'Bricklaying': 'procese',
    'Wall Painting': 'renovari-interioare',
    'Heating Systems': 'procese',
    'Real Estate Consulting': 'spatii-comerciale',
    'Interior Design': 'renovari-interioare',
    'Luxury Finishes': 'renovari-interioare',
    'Electrical Installations': 'procese',
    'Plumbing Installations': 'bai',
    'Thermal Installations': 'procese',
    'Custom Furniture': 'renovari-interioare',
    'Window Installation': 'spatii-comerciale',
    'Door Installation': 'spatii-comerciale',
    'Cleaning Services': 'procese',
  
    // ---- Español ----
    'Aplicación de Yeso': 'renovari-interioare',
    'Instalación de Azulejos': 'bai',
    'Instalación de Baldosas': 'bai',
    'Instalación de Parqué': 'renovari-interioare',
    'Instalación de Pladur': 'renovari-interioare',
    'Instalación de Papel Pintado': 'renovari-interioare',
    'Piedra Natural': 'spatii-comerciale',
    'Escaleras': 'spatii-comerciale',
    'Nivelación de Suelos': 'procese',
    'Pintura': 'renovari-interioare',
    'Albañilería': 'procese',
    'Pintura de Paredes': 'renovari-interioare',
    'Sistemas de Calefacción': 'procese',
    'Consultoría Inmobiliaria': 'spatii-comerciale',
    'Diseño de Interiores': 'renovari-interioare',
    'Acabados de Lujo': 'renovari-interioare',
    'Instalaciones Eléctricas': 'procese',
    'Instalaciones Sanitarias': 'bai',
    'Instalaciones Térmicas': 'procese',
    'Muebles a Medida': 'renovari-interioare',
    'Instalación de Ventanas': 'spatii-comerciale',
    'Instalación de Puertas': 'spatii-comerciale',
    'Servicios de Limpieza': 'procese',
  };
  